include('../lib/index')

storage.clear()
storage.set_item('1111', 23333)
assert(storage.get_item('1111'), 23333)
storage.remove_item('1111')
assert(storage.get_item('1111'), null)
storage.set_item('hello', mem())
storage.set_item('hello1', mem())
storage.set_item('hello2', mem())
let keys = storage.get_keys()
assert(keys.count(), 3)
storage.clear()
keys = storage.get_keys()
assert(keys.count(), 0)
assert(storage.exist('hello'), false)
assert(storage.get_item('hello'),null)