include('./stdafx.as')
include('./kv.as')

storage.clear()
storage.set_item('1111', 23333)
ass(storage.get_item('1111'), 23333)
storage.remove_item('1111')
ass(storage.get_item('1111'), null)
storage.set_item('hello', mem())
storage.set_item('hello1', mem())
storage.set_item('hello2', mem())
let keys = storage.get_keys()
ass(keys.length(), 3)
storage.clear()
keys = storage.get_keys()
ass(keys.length(), 0)
ass(storage.exist('hello'), false)
ass(storage.get_item('hello'),null)