HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 04 Jan 2022 14:34:46 GMT
Server: Apache
Set-Cookie: TIEBAUID=3re43frgf45eg5g4drt5; expires=Thu, 31-Dec-2020 15:59:59 GMT; path=/; domain=tieba.baidu.com
Tracecode: 20222197060045111233442011
Tracecode: 20861970600244895754010422
Vary: Accept-Encoding
X-Xss-Protection: 1; mode=block
Content-Length: 183

{"forum_id":5929704,"is_banned":null,"is_key_op":true,"is_applying":false,"has_intern":false,"candidates_num":0,"unhandled_manager_num":0,"assist_candidates_num":0,"state":"applying"}